# Generated by Django 6.0.3 on 2026-05-15 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_first_name_customuser_last_login_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfirmationCode',
        ),
    ]
