version: '3'
services:
  web:
    container_name: "web"
    build:
      context: .
    ports:
      - '8000:8000' # host:container
    env_file:
      .env
    volumes:
      - .:/app
      - back_media:/app/media
      - back_static:/app/static
    depends_on:
      - db
      - redis
    command: sh /app/entrypoint.sh


  db:
    container_name: "postgres_shop"
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    container_name: "redis_shop"
    image: redis:7
    volumes:
      - redis_data:/data

  celery_worker:
    container_name: "worker_shop"
    build:
      context: .
    env_file:
      .env
    volumes:
      - .:/app
    depends_on:
      - redis
    command: celery -A shop_api worker --loglevel=info

  celery_beat:
    container_name: "beat_shop"
    build:
      context: .
    env_file:
      .env
    volumes:
      - .:/app
    depends_on:
      - redis
    command: celery -A shop_api beat --loglevel=info


  celery_flower:
    container_name: "flower_shop"
    build:
      context: .
    env_file:
      .env
    volumes:
      - .:/app
    depends_on:
      - redis
    command: celery -A shop_api flower --loglevel=info
    ports:
      - "5566:5555"

  nginx:
    container_name: "nginx_shop"
    image: nginx:1.25
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - back_media:/app/media
      - back_static:/app/static

volumes:
  db_data:
  redis_data:
  back_media:
  back_static:
